---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
  name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP
  externalIPs:
  - 192.168.1.250 #Please change the IP
  selector:
    name: mongo
    purpose: NoSql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: mongo
  name: mongo
spec:
  selector:
    matchLabels:
      name: mongo
      purpose: NoSql
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
        purpose: NoSql
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          hostPath:
            path: /home/chico5g/data/NoSql
            type: Directory

