ATTRIBUTE_ID = 'id'
ATTRIBUTE_NAME = 'name'

PROCEDURE_POST_ATTRIBUTE_DEPT = 'dept'
PROCEDURE_POST_ATTRIBUTE_DOCUMENT_ID = 'document_id'
PROCEDURE_POST_ATTRIBUTE_ESCALATION_PLAN = 'escalation_plan'
PROCEDURE_POST_ATTRIBUTE_PURPOSE = 'purpose'
PROCEDURE_POST_ATTRIBUTE_SAFETY_REQ = 'safety_req'
PROCEDURE_POST_ATTRIBUTE_SPEC_REFERENCE = 'spec_reference'
PROCEDURE_POST_ATTRIBUTE_TOOLS = 'tools'
PROCEDURE_POST_ATTRIBUTE_STEPS = 'steps'

PROCEDURE_POST_ATTRIBUTE_LIST = [
    ATTRIBUTE_NAME,
    PROCEDURE_POST_ATTRIBUTE_DEPT,
    PROCEDURE_POST_ATTRIBUTE_DOCUMENT_ID,
    PROCEDURE_POST_ATTRIBUTE_ESCALATION_PLAN,
    PROCEDURE_POST_ATTRIBUTE_PURPOSE,
    PROCEDURE_POST_ATTRIBUTE_SAFETY_REQ,
    PROCEDURE_POST_ATTRIBUTE_SPEC_REFERENCE,
    PROCEDURE_POST_ATTRIBUTE_TOOLS,
    PROCEDURE_POST_ATTRIBUTE_STEPS
]

STEP_POST_ATTRIBUTE_DESCRIPTION = 'description'
STEP_POST_ATTRIBUTE_MEDIA_URL = 'media_url'
STEP_POST_ATTRIBUTE_SEQUENCE_NUMBER = 'sequence_number'
STEP_POST_ATTRIBUTE_TYPE = 'type'

STEP_POST_ATTRIBUTE_LIST = [
    ATTRIBUTE_NAME,
    STEP_POST_ATTRIBUTE_SEQUENCE_NUMBER,
    STEP_POST_ATTRIBUTE_TYPE,
    STEP_POST_ATTRIBUTE_DESCRIPTION
]

ATTRIBUTE_OBJECT_ID = 'object_id'
ATTRIBUTE_OBJECT_NAME = 'object_name'
