---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: prometheus
  name: prometheus
spec:
  ports:
  - name: promui
    port: 9090
    targetPort: 9090
    protocol: TCP
  type: ClusterIP
  externalIPs:
  - 192.168.1.250 #Please change the external IP
  selector:
    app: prometheus
    purpose: monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
    purpose: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
      purpose: monitoring
  template:
    metadata:
      labels:
        app: prometheus
        purpose: monitoring
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus
        volumeMounts:
          - name: config-volume
            mountPath: /etc/prometheus/prometheus.yml
            subPath: prometheus.yml
        ports:
        - containerPort: 9090
      volumes:
        - name: config-volume
          configMap:
           name: prometheus-example-cm

