---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: umflask
  name: umflask
spec:
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  type: ClusterIP
  externalIPs:
  - 192.168.1.250 #Please change the external IP
  selector:
    app: umflask
    purpose: usermanagment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: umflask
spec:
  selector:
    matchLabels:
      app: umflask
      purpose: usermanagment
  replicas: 1
  template:
    metadata:
      labels:
        app: umflask
        purpose: usermanagment
    spec:
      containers:
      - name: umflask
        image: umflask
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
