ATTRIBUTE_ID = 'id'

USER_POST_ATTRIBUTE_NAME = 'name'
USER_POST_ATTRIBUTE_EMAIL = 'email'
USER_POST_ATTRIBUTE_PASSWORD = 'password'
USER_POST_ATTRIBUTE_OLD_PASSWORD = 'old_password'
USER_POST_ATTRIBUTE_LEVEL = 'level'

USER_POST_ATTRIBUTES_LIST = [
    USER_POST_ATTRIBUTE_NAME,
    USER_POST_ATTRIBUTE_EMAIL,
    USER_POST_ATTRIBUTE_PASSWORD
]

USER_LOGIN_ATTRIBUTES_LIST = [
    USER_POST_ATTRIBUTE_EMAIL,
    USER_POST_ATTRIBUTE_PASSWORD
]

SESSION_UPDATE_ATTRIBUTE_STATUS = 'status'
SESSION_UPDATE_ATTRIBUTE_DEVICE_TYPE = 'device_type'
SESSION_UPDATE_ATTRIBUTE_DEVICE_IP = 'device_ip'
SESSION_UPDATE_ATTRIBUTE_HOLOLENS_USERNAME = 'hololens_username'
SESSION_UPDATE_ATTRIBUTE_HOLOLENS_PASSWORD = 'hololens_password'