ERROR_CODE_DUPLICATE_ENTRY = 1062

USER_LEVEL_ENUM_ADMIN = 'ADMIN'
USER_LEVEL_ENUM_TECH_SUPPORT = 'TECH_SUPPORT'
USER_LEVEL_ENUM_REMOTE_OPERATOR = 'REMOTE_OPERATOR'
USER_LEVEL_ENUM_READ_ONLY = 'READ_ONLY'

USER_LEVEL_ENUM_LIST = [
    USER_LEVEL_ENUM_READ_ONLY,
    USER_LEVEL_ENUM_TECH_SUPPORT,
    USER_LEVEL_ENUM_REMOTE_OPERATOR
]

SESSION_STATUS_ENUM_ONLINE = 'ONLINE'
SESSION_STATUS_ENUM_OFFLINE = 'OFFLINE'
SESSION_STATUS_ENUM_BUSY = 'BUSY'

UPDATE_SESSION_STATUS_ENUM_LIST = [
    SESSION_STATUS_ENUM_ONLINE,
    SESSION_STATUS_ENUM_BUSY
]

SESSION_DEVICE_TYPE_ENUM_HOLOLENS = 'HOLOLENS'
SESSION_DEVICE_TYPE_ENUM_ANDROID = 'ANDROID'

SESSION_DEVICE_TYPE_ENUM_LIST = [
    SESSION_DEVICE_TYPE_ENUM_HOLOLENS,
    SESSION_DEVICE_TYPE_ENUM_ANDROID
]
